name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Copy file
      uses: canastro/copy-action@0.0.2
      with:
        # Source file
        source: build.env
        # Target file
        target: .env
      
    - name: Npm
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - run: npm install
    - run: npm run-script build:prod 

    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        # The name of the directory you want to upload
        source_dir: dist
        # The name of the storage account container these assets will be uploaded to
        container_name: $web
        # The connection string for the storage account
        connection_string: secrets.WEB_STORAGE_CONNECTION
        # extra arguments that can be passed to `az storage blob upload-batch`. Useful for passing flags like `--pattern` or `--destination-path`
        #extra_args: # optional

      env:
        CI: true
        #CLIENT_ID: a3b2710ee3234a5bb1c9c6ec99b201ed 
        #REDIRECT_URI: https://roguesoundweb.z16.web.core.windows.net
